### ISSUE TITLE
[Feature] Support for Importing / Exporting custom schemes

### ISSUE THREAD

**Issue by BaBrixx** [ECDAR-AAU-SW-P5/Ecdar-GUI-Web#165] opened 2023-12-13 13:55 UTC
### Suggestion
The user should be able to export and import color schemes between browsers. This would make it much easier to backup color schemes and potentially allow for sharing schemes between users.

This functionality should either be introduced as part of the toolbar in the top or as buttons in each of the settings tab.

**Comment by SolarEarth37** [comment] 2023-12-15 12:50
This seems to be the same issue as #157. Correct me if i'm wrong

**Comment by atjn** [comment] 2023-12-19 19:57
Agreed, this is a duplicate of #157

**Closed by atjn** 2023-12-19 19:57 UTC
Labels: enhancement
